<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>	

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />

    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FChassis.Core\FChassis.Core.csproj" />
  </ItemGroup>
</Project>
